kumuluzee:
  name: catalog-ms
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/CatalogDS
      connection-url: jdbc:postgresql://localhost:5432/catalog
      username: dbuser
      password: postgres
      pool:
        max-size: 1
  cors-filter:
    annotations:
      my-resource:
        allow-origin: "*"
        allow-subdomains: true
  metrics:
    web-instrumentation:
      - name: catalog-endpoint
        url-pattern: /v1/catalog/*
  openapi-mp:
    ui:
      server-auto-config:
        enabled: true
        original-uri-check: true
    servers: http://20.23.109.163/product-catalog/
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                            <Configuration name="comments">
                                <Appenders>
                                    <Console name="console" target="SYSTEM_OUT">
                                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                    </Console>
                                    <Socket name="logstash" host="19df88b2-7195-4c74-a177-15522fddde1b-ls.logit.io"
                                    port="27827" protocol="udp">
                                        <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                    </Socket>
                                </Appenders>
                                <Loggers>
                                    <!-- Default logger -->
                                    <Root level="all">
                                        <AppenderRef ref="console" level="info" />
                                        <AppenderRef ref="logstash" level="trace" />
                                    </Root>
                                </Loggers>
                            </Configuration>'

rest-properties:
  maintenance-mode: false
  broken: false